<hr style="margin-bottom: 40px;">

# NumPy exercises


Import Numpy Package

In [28]:
# your code goes here
import numpy as np

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

Crie uma matriz numpy de tamanho 10, preenchida com zeros.

In [35]:
# your code goes here
matriz = np.zeros(10)
print(matriz)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie um array numpy com valores variando de 10 a 49

In [36]:
# your code goes here
array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy de 2 X 2 inteiros, preenchida com somente número 1.

In [37]:
# your code goes here
matriz = np.ones((2, 2), dtype=int)
print(matriz)

[[1 1]
 [1 1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy de 3 X 2 números flutuantes, preenchidos com número 1.

In [38]:
# your code goes here
matriz = np.ones((3, 2), dtype=float)
print(matriz)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, crie uma nova matriz numpy com a mesma forma e tipo de X, mas preenchida preenchida com número 1.

_Dica: ones_like()_

In [48]:
X = np.arange(4,dtype=int)
# your code goes here
nova_matriz = np.ones_like(X)
print(nova_matriz)

[1 1 1 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz numpy X, crie uma nova matriz numpy com a mesma forma e tipo de X, mas preenchida preenchida com zeros.

_Dica: zero_likes()_

In [49]:
X = np.array([[1,2,3],[4,5,6]], dtype=int)
# your code goes here
nova_matriz = np.zeros_like(X)
print(nova_matriz)

[[0 0 0]
 [0 0 0]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy de 4X4 inteiros, preenchida com cincos.

In [50]:
# your code goes here
matriz = np.full((4, 4), 5, dtype=int)
print(matriz)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz numpy X, crie uma nova matriz numpy com a mesma forma e tipo de X, preenchida com setes.

In [51]:
X = np.array([[2,3],[6,2]],dtype=np.int16)
# your code goes here
new_matriz = np.full_like(X, 7)
print(new_matriz)

[[7 7]
 [7 7]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy de identidade 3 X 3 (1 na diagonal e o ao redor)

In [52]:
# your code goes here
matriz_identidade = np.eye(3, dtype=int)
print(matriz_identidade)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy, preenchida com 3 valores inteiros aleatórios entre 1 e 10.

_Dica: random_

In [55]:
# your code goes here
matriz = np.random.randint(1, 11, size=3)
print(matriz)

[1 6 8]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy **3 X 3 X 3**, preenchida com valores _float_ aleatórios.

In [56]:
# your code goes here
matriz = np.random.rand(3, 3, 3)
print(matriz)

[[[0.01147942 0.33481426 0.91383058]
  [0.41223483 0.38352863 0.7836821 ]
  [0.19102451 0.18368501 0.94668891]]

 [[0.32141472 0.06284363 0.79389671]
  [0.38019404 0.74634749 0.55800079]
  [0.56418145 0.98926788 0.86893579]]

 [[0.90010771 0.68892098 0.36738516]
  [0.72543093 0.91250837 0.06210486]
  [0.58441955 0.45351828 0.11613966]]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a lista X python, converta-a em uma matriz Y numpy

In [58]:
X= [1,2,3,4]
print(X, type(X))

# your code goes here
matriz = np.array(X)
print(matriz)

[1, 2, 3, 4] <class 'list'>
[1 2 3 4]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, faça uma cópia e armazene-a em Y.

_Dica: copy()_

In [ ]:
X = np.array([5,2,3],dtype =np.int16)
print(X, id(X))

# your code goes here
Y = X.copy()

[5 2 3] 2355130417296
[5 2 3] 2355130417200


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie um array numpy com números de 1 a 10

In [ ]:
# your code goes here
array_numeros = np.arange(1, 11)
print(array_numeros)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy com os números ímpares entre 1 a 10

In [68]:
# your code goes here
array_numeros = np.arange(1, 11, 2)
print(array_numeros)

[1 3 5 7 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie um array numpy com números de 1 a 10, em ordem decrescente.

In [72]:
# your code goes here
array_numeros = np.arange(10, 0, -1)
print(array_numeros)

[10  9  8  7  6  5  4  3  2  1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy 3 X 3, preenchida com valores variando de 0 a 8

In [74]:
matriz = np.arange(9).reshape(3, 3)
print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


Dado o array X numpy, mostre seu primeiro elemento

In [75]:
X = np.array(['A','B','C','D','E'])
# your code goes here
primeiro = X[0]
print(primeiro)

A


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre seu último elemento

In [ ]:
X = np.array(['A','B','C','D','E'])
# your code goes here
valor = X[-1]
print(valor)

E


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre seus três primeiros elementos

In [ ]:
X = np.array(['A','B','C','D','E'])
# remember! elements start at zero index
# your code goes here
valor = X[0:3]
print(valor)

['A' 'B' 'C']


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre todos os elementos do meio

In [ ]:
X = np.array(['A','B','C','D','E'])
# your code goes here
valor = X[1:-1]
print(valor)

['B' 'C' 'D']


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os elementos na posição reversa

In [81]:
X = np.array(['A','B','C','D','E'])
# your code goes here
valor = X[::-1]
print(valor)

['E' 'D' 'C' 'B' 'A']


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os elementos de posição ímpar

In [82]:
X = np.array(['A','B','C','D','E'])
# your code goes here
valor = X[1::2]
print(valor)

['B' 'D']


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os elementos da primeira linha

In [87]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# your code goes here
valor = X[0]
print(valor)

[1 2 3 4]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os últimos elementos da linha

In [88]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
# your code goes here
valor = X[:,-1]
print(valor)

[ 4  8 12 16]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre o primeiro elemento na primeira linha

In [89]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# your code goes here
valor = X[0,0]
print(valor)

1


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre o último elemento na última linha

In [90]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
# your code goes here
valor = X[-1,-1]
print(valor)

16


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os elementos da linha do meio

In [91]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
# your code goes here
valor = X[1:-1]
print(valor)

[[ 5  6  7  8]
 [ 9 10 11 12]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os dois primeiros elementos nas duas primeiras linhas

In [92]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
# your code goes here
valor = X[0:2, 0:2]
print(valor)

[[1 2]
 [5 6]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os dois últimos elementos nas duas últimas linhas

In [95]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
# your code goes here
resultado = X[-2:, -2:]
print(resultado)

[[11 12]
 [15 16]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


Converta o lista de inteiros para numpy array do tipo float

_Dica: float_

In [97]:
X = [-5, -3, 0, 10, 40]
# your code goes here
array_float = np.array(X, dtype=float)
print(array_float)

[-5. -3.  0. 10. 40.]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Inverta a matriz numpy fornecida (o primeiro elemento se torna o último)

In [98]:
X = [-5, -3, 0, 10, 40]
# your code goes here
X_invertido = X[::-1]
print(X_invertido)

[40, 10, 0, -3, -5]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Ordenar (classificar) o array numpy dado

_Dica: sort()_

In [99]:
X = [0, 10, -5, 40, -3]
# your code goes here
X.sort()
print(X)

[-5, -3, 0, 10, 40]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, defina o quinto elemento igual a 1

In [100]:
X = np.zeros(10)
# your code goes here
X[4] = 1
print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, altere 50 por 40

In [101]:
X = np.array([10, 20, 30, 50])
# your code goes here
X[X == 50] = 40
print(X)

[10 20 30 40]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, altere a última linha com todos os 1

In [102]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
# your code goes here
X[-1, :] = 1
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

 Dada a matriz X numpy, troque o último item da última linha por 0

In [103]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
# your code goes here
X[-1, -1] = 0
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15  0]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, adicione 5 a cada elemento

In [104]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
# your code goes here
X = X + 5
print(X)

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


Dada a matriz X numpy, faça uma variável chamada mask que mostre verdadeiro para valores negativos e falso para valores positivos

In [105]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
# your code goes here
mask = X < 0
print(mask)

[ True False False  True False False False False  True False]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, obtenha os elementos negativos

In [106]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
# your code goes here
negativos = X[X < 0]
print(negativos)

[-1 -4 -9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, obtenha números maiores que 5

In [107]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
# your code goes here
maiores_que_5 = X[X > 5]
print(maiores_que_5)

[ 6 10]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, obtenha números maiores que a média dos elementos

_Dica: mean()_

In [108]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
# your code goes here
media = X.mean()
maiores_que_media = X[X > media]
print(maiores_que_media)

[ 2  5  6 10]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, obtenha números iguais a 2 ou 10

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
# your code goes here
resultado = X[(X == 2) | (X == 10)]
print(resultado)

[ 2 10]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


Dada a matriz X numpy, retorne True se nenhum de seus elementos for zero

_Dica: all()_

In [110]:
X = np.array([-1, 2, 1, -4, 5, 6, 7, 8, -9, 10])
# your code goes here
nenhum_zero = (X != 0).all()
print(nenhum_zero)

True


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, retorne True se algum de seus elementos for zero

_Dica: any()_

In [111]:
X = np.array([0,0,0,0,0,0])
# your code goes here
algum_zero = (X == 0).any()
print(algum_zero)

True


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

Dada a matriz X numpy, mostre a soma de seus elementos

_Dica: sum()_

In [112]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
# your code goes here
soma_total = X.sum()
print(soma_total)

43


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dado o array X numpy, mostre o valor médio de seus elementos

_Dica: mean()_

In [113]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
# your code goes here
media = X.mean()
print(media)

3.7


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre a soma de suas colunas

remember !!!
- axis=0 columns 
- axis=1 rows

In [114]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
# your code goes here
soma_colunas = X.sum(axis=0)
print(soma_colunas)

[28 32 36 40]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre o valor médio de suas linhas

In [115]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
# your code goes here
media_linhas = X.mean(axis=1)
print(media_linhas)

[ 2.5  6.5 10.5 14.5]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre o valor máximo de seus elementos

In [116]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
# your code goes here
valor_maximo = X.max()
print(valor_maximo)

10


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)